mpiexec -np 1 ./matmul4
mpiexec -np 1 ./matmul4 
mpiexec -np 1 ./matmul4 
mpiexec -np 4 ./matmul4 
mpiexec -np 4 ./matmul4 
mpiexec -np 4 ./matmul4 
mpiexec -np 9 ./matmul4 
mpiexec -np 9 ./matmul4 
mpiexec -np 9 ./matmul4 
mpiexec -np 16 ./matmul4 
mpiexec -np 16 ./matmul4 
mpiexec -np 16 ./matmul4 
mpiexec -np 25 ./matmul4 
mpiexec -np 25 ./matmul4 
mpiexec -np 25 ./matmul4 
